donation_index:
    path:     /
    defaults: { _controller: "AppBundle:Donation:index" }
    methods:  GET

donation_new:
    path:     /new
    defaults: { _controller: "AppBundle:Donation:new" }
    methods:  [GET, POST]

donation_edit:
    path:     /printed/{id}
    defaults: { _controller: "AppBundle:Donation:printed" }
    methods:  [GET, POST]