donation_index:
    path:     /
    defaults: { _controller: "AppBundle:Donation:index" }
    methods:  [GET, OPTIONS]

donation_new:
    path:     /new
    defaults: { _controller: "AppBundle:Donation:new" }
    methods:  [GET, POST, OPTIONS]