sticker_index:
    path:     /
    defaults: { _controller: "AppBundle:Sticker:index" }
    methods:  GET

sticker_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Sticker:show" }
    methods:  GET

sticker_new:
    path:     /new
    defaults: { _controller: "AppBundle:Sticker:new" }
    methods:  [GET, POST]

sticker_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Sticker:edit" }
    methods:  [GET, POST]

sticker_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Sticker:delete" }
    methods:  DELETE
