app_sticker:
    resource: "@AppBundle/Resources/config/routing/sticker.yml"
    prefix:   /sticker

app_donation:
    resource: "@AppBundle/Resources/config/routing/donation.yml"
    prefix:   /donation

root :
    path : /
    defaults: {_controller: AppBundle:Default:greet}

