AppBundle\Entity\Donation:
    type: entity
    table: donation
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        amount:
            type: float
        paypalTransactionId:
            type: string
        creation_date:
            type: date
        printed:
            type: integer
            length: 1
    oneToOne:
        sticker:
            targetEntity: AppBundle\Entity\Sticker
            inversedBy: donation
            joinColumn:
                name: sticker_id
                referencedColumnName: id